# Admin Function
@hostname = http://localhost:21465
@token = Bearer $2b$10$dDB2UD8Fk50.5O1W6NA9geGxuY8GWFZvbOtKTaQKMme29Rpr0xx1i
@session = personal
@secretKey = THISISMYSECURETOKEN

### Genereate Token
POST {{hostname}}/api/{{session}}/{{secretKey}}/generate-token

###############################################################################################

# Session Function

### Start Session
POST {{hostname}}/api/{{session}}/start-session
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

### Close Session
POST {{hostname}}/api/{{session}}/close-session
Accept: application/json;
Content-Type: application/json;
Authorization: {{token}}

###############################################################################################

# Message Functions

### Send Message
POST {{hostname}}/api/{{session}}/send-message
Content-Type:application/json; charset=utf-8
Accept: application/json
Authorization: {{token}}

{
  "phone": "5511982743910,5511982743910,5511982743910,5511982743910,5511982743910,5511982743910,5511982743910,5511982743910,5511982743910",
  "message": "*Abner* Rodrigues"
}

### Send Image
POST {{hostname}}/api/{{session}}/send-image
Content-Type:application/json; charset=utf-8
Accept: application/json
Authorization: {{token}}

{
  "phone": "5511982743910",
  "caption": "*Abner* Rodrigues",
  "path": "C:\\path\\image.png",
  "isGroup": false
}

### Send File
POST {{hostname}}/api/{{session}}/send-file
Content-Type:application/json; charset=utf-8
Accept: application/json
Authorization: {{token}}

{
  "phone": "5511982743910",
  "path": "C:\\path\\image.png",
  "isGroup": false
}

###############################################################################################

# Group Functions

### Create Group
POST {{hostname}}/api/{{session}}/create-group
Content-Type:application/json; charset=utf-8
Accept: application/json
Authorization: {{token}}

{
  "phone": "5511982743910",
  "groupname": "Group Name"
}

### Join Group with InviteCode
POST {{hostname}}/api/{{session}}/join-code
Content-Type:application/json; charset=utf-8
Accept: application/json
Authorization: {{token}}

{
  "inviteCode": "Invite Code"
}

#############################################################################################

# Device Functions

### Change Username
POST {{hostname}}/api/{{session}}/change-username
Content-Type:application/json; charset=utf-8
Accept: application/json
Authorization: {{token}}

{
  "name": "New Username"
}

### Change Profile Image
POST {{hostname}}/api/{{session}}/change-profile-image
Content-Type:application/json; charset=utf-8
Accept: application/json
Authorization: {{token}}

{
  "path": "C:\\path\\image.png"
}

### Change Profile Image
GET {{hostname}}/api/{{session}}/show-all-contacts
Content-Type:application/json; charset=utf-8
Accept: application/json
Authorization: {{token}}